/*
* Copyright (c) 2024 ACOINFO CloudNative Team.
* All rights reserved.
*
* Detailed license information can be found in the LICENSE file.
*
* File: err.h .
*
* Date: 2024-02-20
*
* Author: Yan.chaodong <yanchaodong@acoinfo.com>
*
*/

#ifndef _VSOA_SDK_ERR_H_
#define _VSOA_SDK_ERR_H_

enum ENUM_VSOA_ERR {
    VSOA_OK = 0,
    VSOA_SYS_FAILED_BASE = 10000,
    VSOA_INVALID_PARAM,
    VSOA_UNKNOW_FAILED,
    VSOA_UNKNOWN_FAILED = VSOA_UNKNOW_FAILED,
    VSOA_SYS_FAILED,
    VSOA_SRV_FAILED_BASE = 11000,
    VSOA_SRV_CREATE_FAILED,
    VSOA_SRV_START_FAILED,
    VSOA_SRV_GETADDR_FAILED,
    VSOA_SRV_UNINITED_FAILED,
    VSOA_SRV_REPLY_FAILED,
    VSOA_SRV_PUBLISH_FAILED,
    VSOA_SRV_NOT_SUBSCRIBED,
    VSOA_SRV_DATAGRAM_FAILED,
    VSOA_CLI_FAILED_BASE = 12000,
    VSOA_CLI_AUTO_START_FAILED,
    VSOA_CLI_SETUP_FAILED,
    VSOA_CLI_CREAT_FAILED,
    VSOA_CLI_NOT_CONNECTED,
    VSOA_CLI_CONN_TIMEOUT,
    VSOA_CLI_CALL_TIMEOUT,
    VSOA_CLI_SYNCCALL_FAILED,
    VSOA_CLI_RPCCALL_FAILED,
    VSOA_CLI_HOST_NOTFOUND,
    VSOA_CLI_RESP_TRY_AGAIN,
    VSOA_CLI_RESP_NO_REQID,
    VSOA_CLI_RESP_TIMEOUT,
    VSOA_CLI_RESP_INVALID,
    VSOA_CLI_SUB_NOSERVER,
    VSOA_CLI_SUB_FAILED,
    VSOA_CLI_UNSUB_URL,
    VSOA_CLI_DATAGRAM_FAILED,
    VSOA_CLI_ALLOC_MEMORY_FAILED,
    VSOA_AUTH_FAILED_BASE = 13000,
    VSOA_TOKEN_GETFAILED,
    VSOA_TOEKN_NOT_PERMITTED,
    VSOA_TOKEN_NOT_PERMITTED = VSOA_TOEKN_NOT_PERMITTED,
    VSOA_MASTER_CLI_REGISTER_FAILED = 14000,
    VSOA_TIMER_CREAT_FAILED
};

#endif // _VSOA_SDK_ERR_H_

/*
 * end
 */
